import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from 'next/font/google'
import { ThemeProvider  } from '@mui/material/styles';
import theme from './theme';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <AppRouterCacheProvider  options={{ key: 'css' }}>
        <ThemeProvider theme={theme}>

        {children}
        </ThemeProvider>
        </AppRouterCacheProvider>

        </body>
    </html>
  )
}
